# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  #==============================================================================
  # Windows
  #==============================================================================
  - job: BuildOnWindows

    pool:
      vmImage: "windows-2019"

    steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'
      
      - checkout: self
        displayName: "Checkout git submodules."
        submodules: true

      - task: UniversalPackages@0
        displayName: 'Download LLVM pre-built library'
        inputs:
          command: 'download'
          downloadDirectory: '$(System.DefaultWorkingDirectory)\llvmorg-11.1.0-prebuilt'
          feedsToUse: 'internal'
          vstsFeed: 'ba320e28-41cf-4d2a-978b-e402725ee2cb/63c926aa-419b-4b46-b5c8-440b0a16e0a0'
          vstsFeedPackage: '33fc021f-3ef9-4286-8260-d9969af25fac'
          vstsPackageVersion: '0.0.1'
          verbosity: 'Information'

      - script: |
          mkdir "build-with-prebuilt\build"
          cd    "build-with-prebuilt\build"
          cmake .. -DLLVM_INSTALL_DIR=$(System.DefaultWorkingDirectory)\llvmorg-11.1.0-prebuilt
          cmake --build . --config Release
        displayName: 'Build this project'

  #==============================================================================
  # Linux
  #==============================================================================
  - job: BuildOnLinux

    pool:
      vmImage: "ubuntu-20.04"

    steps:      
      - checkout: self
        displayName: "Checkout git submodules."
        submodules: true

      - task: UniversalPackages@0
        displayName: 'Download LLVM pre-built library'
        inputs:
          command: 'download'
          downloadDirectory: '$(System.DefaultWorkingDirectory)/llvmorg-11.1.0-prebuilt'
          feedsToUse: 'internal'
          vstsFeed: 'ba320e28-41cf-4d2a-978b-e402725ee2cb/901ceb81-0f0f-4a44-898b-880ad087d6ad'
          vstsFeedPackage: 'c4e829d7-a0d4-4728-a5bb-b44bc6431fc0'
          vstsPackageVersion: '0.0.1'
          verbosity: 'Information'

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'Get-ChildItem -Recurse $(System.DefaultWorkingDirectory)/llvmorg-11.1.0-prebuilt | Select-Object -ExpandProperty fullname'

      - script: |
          mkdir "build-with-prebuilt/build" -p
          cd    "build-with-prebuilt/build"
          cmake .. -DLLVM_INSTALL_DIR=$(System.DefaultWorkingDirectory)/llvmorg-11.1.0-prebuilt
          cmake --build . --config Release
        displayName: 'Build this project'
