# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  #==============================================================================
  # Windows
  #==============================================================================
  - job: BuildOnWindows

    pool:
      vmImage: "vs2017-win2016"

    steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'
      
      - checkout: self
        displayName: "Checkout git submodules."
        submodules: true

      - task: UniversalPackages@0
        inputs:
          command: 'download'
          downloadDirectory: '$(System.DefaultWorkingDirectory)'
          feedsToUse: 'internal'
          vstsFeed: 'ba320e28-41cf-4d2a-978b-e402725ee2cb/1ff061a9-e8ce-4c9d-9070-c175f2bd0abf'
          vstsFeedPackage: '8bc2d250-3dc3-4c03-a433-e799e88038aa'
          vstsPackageVersion: '0.0.1'
          verbosity: 'Information'          

      - task: CMake@1
        inputs:
          workingDirectory: 'build-with-prebuilt'
          cmakeArgs: '-G"Ninja" -B"build-with-prebuilt/build" -DCMAKE_BUILD_TYPE=Release build-with-prebuilt'
          
      - task: CMake@1
        inputs:
          workingDirectory: 'build-with-prebuilt'
          cmakeArgs: '--build build-with-prebuilt/build'
           