# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: "windows-2019"

steps:

  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - powershell: |
      $wc = New-Object net.webclient
      $wc.Downloadfile("https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe", "Miniconda3-latest-Windows-x86_64.exe")
      Start-Process "Miniconda3-latest-Windows-x86_64.exe" "/S /D=C:\Miniconda3" -Wait
    displayName: 'Install miniconda'
  
  - powershell: ls -Recurse C:\Miniconda3