# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  #==============================================================================
  # Windows
  #==============================================================================
  - job: BuildOnWindows

    pool:
      vmImage: "windows-2019"

    steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'
      
      - checkout: self
        displayName: "Checkout git submodules."
        submodules: true

      # - task: PowerShell@2
      #   inputs:
      #     targetType: 'inline'
      #     script: 'Get-ChildItem -Recurse c:\ | Select-Object -ExpandProperty fullname'

      # - task: PowerShell@2
      #   inputs:
      #     targetType: 'inline'
      #     script: 'Get-ChildItem -Recurse "C:\Program Files (x86)\Microsoft Visual Studio" | Select-Object -ExpandProperty fullname'
      
      - task: UniversalPackages@0
        displayName: 'Download LLVM pre-built library'
        inputs:
          command: 'download'
          downloadDirectory: '$(System.DefaultWorkingDirectory)\llvmorg-11.1.0-vs2019-x64-rel'
          feedsToUse: 'internal'
          vstsFeed: 'ba320e28-41cf-4d2a-978b-e402725ee2cb/63c926aa-419b-4b46-b5c8-440b0a16e0a0'
          vstsFeedPackage: '33fc021f-3ef9-4286-8260-d9969af25fac'
          vstsPackageVersion: '0.0.1'
          verbosity: 'Information'
          

      - script: |
          mkdir "build-with-prebuilt\build"
          cd    "build-with-prebuilt\build"
          cmake .. -DLLVM_INSTALL_DIR=$(System.DefaultWorkingDirectory)\llvmorg-11.1.0-vs2019-x64-rel
          cmake --build . --config Release
        displayName: 'Build this project'
