# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  #==============================================================================
  # Windows
  #==============================================================================
  - job: BuildOnWindows

    pool:
      vmImage: "windows-2019"

    steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'
      
      - checkout: self
        displayName: "Checkout git submodules."
        submodules: true

      - task: UniversalPackages@0
        displayName: 'Download LLVM pre-built library'
        inputs:
          command: 'download'
          downloadDirectory: '$(System.DefaultWorkingDirectory)\llvmorg-11.1.0-vs2019-x64-rel'
          feedsToUse: 'internal'
          vstsFeed: 'ba320e28-41cf-4d2a-978b-e402725ee2cb/071d0cac-732f-4f21-96a0-556b3a80231f'
          vstsFeedPackage: '74c2877d-d14a-4bfa-aa51-fbc77173ffac'
          vstsPackageVersion: '0.0.1'
          verbosity: 'Information'

      - script: |
          mkdir build
          cd build
          cmake "build-with-prebuilt" -B"build-with-prebuilt\build" -DLLVM_INSTALL_DIR=$(System.DefaultWorkingDirectory)\llvmorg-11.1.0-vs2019-x64-rel
          cmake --build "build-with-prebuilt\build" --config Release
        displayName: 'Build this project'

      #- task: CMake@1
      #  inputs:
      #    cmakeArgs: '-G"Visual Studio 16 2019" -B"build" -A X64 -DLLVM_INSTALL_DIR=$(System.DefaultWorkingDirectory)\llvmorg-11.1.0-vs2019-x64-rel'
      
      #- task: CMake@1
      #  inputs:
      #    cmakeArgs: '--build build --config Release'