# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  #==============================================================================
  # Windows
  #==============================================================================
  - job: BuildOnWindows

    pool:
      vmImage: "vs2017-win2016"

    steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'
      
      - checkout: self
        displayName: "Checkout git submodules."
        submodules: true
        
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'choco install ninja -YES'
          pwsh: true
      
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'ninja --version'
          pwsh: true

      - task: UniversalPackages@0
        inputs:
          command: 'download'
          downloadDirectory: '$(System.DefaultWorkingDirectory)'
          feedsToUse: 'internal'
          vstsFeed: 'ba320e28-41cf-4d2a-978b-e402725ee2cb/6d62ceca-2686-4258-b4a2-77904450321b'
          vstsFeedPackage: '1534adb7-4c50-41d4-b2cd-00fd0c90a9a7'
          vstsPackageVersion: '0.0.1'
          verbosity: 'Information'

      - task: CMake@1
        inputs:
          workingDirectory: 'build-with-prebuilt'
          cmakeArgs: '-G"Ninja" -B"build -DLLVM_INSTALL_DIR=$(System.DefaultWorkingDirectory) -DCMAKE_BUILD_TYPE=Release'
          
      - task: CMake@1
        inputs:
          workingDirectory: 'build-with-prebuilt/build'
          cmakeArgs: '--build . --config Release'
           